server:
  port: 11000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: hospital-outpatientfinancial
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/outpatientfinancial/*.xml
  global-config:
    db-config:
      id-type: auto
